name: mirrorchyan_release

on:
  workflow_dispatch:
    inputs:
      tag:
        default: ''
        required: false
#   release:
#     types: [published]

jobs:
  mirrorchyan:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        os: [win]
        arch: [x86_64]
    steps:
      - uses: MirrorChyan/uploading-action@v1
        with:
          filetype: latest-release
          filename: ${{ format('MaaADr-{0}-{1}-*.zip', matrix.os, matrix.arch) }}
          mirrorchyan_rid: MaaADr
          tag: ${{ inputs.tag }}

          os: ${{ matrix.os }}
          arch: ${{ matrix.arch }}

          owner: Azureetude
          repo: MaaADr
          github_token: ${{ secrets.GITHUB_TOKEN }}
          upload_token: ${{ secrets.MirrorChyanUploadToken }}
